server:
  port: 9090
  
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gce?useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: gce
    password: gce
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  thymeleaf:
    cache: false